### ISSUE TITLE
Geração de Hash no último parâmetro

### ISSUE THREAD

**Issue by rcoproc** [josuelima/sped2sql#2]
Olá Josué boa noite.

Parabéns por esta GEM  está me ajudando e muito em um trabalho que estou fazendo com importação de EFD icms ipi.

Estou com duas dúvidas ou problemas quem sabe vc possa me dar umas dicas:

1. Tem um Hash no último atributo do insert , temo como tirar este parâmetro ?? veja:
/*!40000 ALTER TABLE `0990` DISABLE KEYS */;
INSERT INTO 0990 VALUES ('','0990','4065','**b110429e-9ed9-4d82-b6e6-272a027c23e7**');
/*!40000 ALTER TABLE `0990` ENABLE KEYS */;

2. Os inserts estão com uma tabela do tipo 0990 e nos esquemas( em postgresql )  do seu outro projeto  as tabelas são criadas como reg_0990 ,  remo como eu definir o sufixo das tabelas na geração do método, to_sql  veja:

--
-- Registro: 0990
--

CREATE TABLE "reg_0990" (
  "ID" bigint NOT NULL,
  "REG" varchar(4) DEFAULT NULL,
  "QTD_LIN_0" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("ID")
);

Abraço e obrigado se puder responder.

Ricardo Oliveira

**Comment by josuelima** [comment]
Ola @rcoproc, que bom que o projeto tem lhe ajudado.

1 - Sim, da pra voce tirar esse Hash. Na verdade eh so nao acrescentar ele. Quando uma nova instancia do Conversor eh criada, os parsers NormalizaSQL e AddHash sao adicionados por padrao: https://github.com/josuelima/sped2sql/blob/master/lib/sped2sql/conversor.rb#L23
Vc so precisaria deixar explicito que nao quer ele. Isso deve ser suficiente: 
```ruby 
conversor = SPED2SQL::Conversor.new(arquivo_sped, arquivo_mapa, {tasks: [SPED2SQL::Pipeline::NormalizaSQL]})
```

2 - Sim, vc pode definir um sufixo e um prefixo para os nomes das tabelas.
No exemplo a seguir, vc estaria excluindo o Hash e adicionando um prefix e sufixo a todos os nomes de tabela na hora do insert:
```ruby
conversor = SPED2SQL::Conversor.new(arquivo_sped, arquivo_mapa, {tasks: [SPED2SQL::Pipeline::NormalizaSQL], tbl_prefix: "reg_", tbl_sufix: "_algum_sufixo"})
```

Abs
